"""Send each .tex file to Gemini 2.5 Flash for readability suggestions.
Does NOT rewrite — just flags what to improve and why.
"""
import sys, os
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from dotenv import load_dotenv
load_dotenv(override=True)

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
PAPER_DIR = Path(__file__).parent.parent / "publish" / "surf_revised_new"
OUT_DIR = Path(__file__).parent.parent / "outputs"
OUT_FILE = OUT_DIR / "gemini_readability_review.md"

FILES = [
    "sec_abstract.tex",
    "sec_intro.tex",
    "sec_related.tex",
    "sec_methodology.tex",
    "sec_results.tex",
    "sec_discussion.tex",
    "sec_conclusion.tex",
]

SYSTEM_PROMPT = """You are an expert academic copyeditor reviewing a computer science paper for CCNC 2026 (IEEE double-column format). The paper uses the Master-cai academic writing guidelines: one paragraph = one message, topic sentences first, self-contained nouns (no orphaned pronouns like "This" or "It"), no em dashes, no filler words.

Your job: Read the LaTeX source below and suggest how to make it MORE HUMAN-READABLE. Do NOT change the meaning, content, data, or findings. Only flag issues with:
1. Sentences that are too long or hard to parse — suggest a split
2. Orphaned pronouns ("This", "It", "These") without a clear noun referent
3. Paragraphs that mix multiple ideas — suggest splitting
4. Technical jargon that could be clearer
5. Redundant or repeated phrasing
6. Any sentence where the reader would need to re-read to understand

Format your response as:
### File: <filename>

**Line ~N:** "<original phrase>"
→ Issue: <what's wrong>
→ Fix: "<suggested rewrite>" (or "Consider: <alternative>")

Only flag real problems. Skip things that are fine. Be specific — quote exact phrases."""


def call_gemini(filename, content):
    """Send one file to Gemini, return suggestions."""
    try:
        from google import genai as google_genai
    except ImportError:
        print("  google-genai not installed")
        return None

    user = f"File: {filename}\n\n```latex\n{content}\n```"
    combined = f"{SYSTEM_PROMPT}\n\n{user}"

    try:
        client = google_genai.Client(api_key=GEMINI_API_KEY)
        resp = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=combined,
        )
        if resp and resp.text:
            return resp.text
        print(f"  Empty response for {filename}")
        return None
    except Exception as e:
        print(f"  Error for {filename}: {e}")
        return None


def main():
    if not GEMINI_API_KEY:
        print("ERROR: GEMINI_API_KEY not set")
        sys.exit(1)

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    all_results = []
    for fname in FILES:
        fpath = PAPER_DIR / fname
        if not fpath.exists():
            print(f"  SKIP {fname} (not found)")
            continue

        content = fpath.read_text()
        lines = content.count('\n')
        print(f"  [{fname}] {lines} lines → Gemini...", flush=True)

        result = call_gemini(fname, content)
        if result:
            all_results.append(f"## {fname}\n\n{result}\n")
            print(f"    ✓ got {len(result)} chars", flush=True)
        else:
            all_results.append(f"## {fname}\n\n*(Gemini returned no suggestions)*\n")
            print(f"    ✗ no response", flush=True)

    # Write combined output
    header = f"""# Gemini Readability Review — SURF Paper
Generated by Gemini 2.5 Flash on {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')}

**Instructions:** Review each suggestion. Apply fixes that improve readability
without changing meaning. Ignore suggestions that would alter content.

---

"""
    OUT_FILE.write_text(header + "\n---\n".join(all_results))
    print(f"\nDone → {OUT_FILE}")


if __name__ == "__main__":
    main()
